### ISSUE TITLE
localization settings: separator for 1000 and decimal 

### ISSUE THREAD

**Issue by palindromi** [Tinkerforge/warp-charger#1]
due to different localization settings, there are different charaters used for
decimal sign (DE: ',' US: '.')
separator for 1000 ( DE: '.', US: ',')

and a Ladestrom (german) of 32.000 A would be 1000x more than the 32 shown else in the UI.

Please check for the printing of floating numbers.

See [Ladecontroller Zustand](https://imgur.com/a/rD3y81u)
![Ladecontroller Zustand](https://imgur.com/a/rD3y81u)

**Comment by rtrbt** [comment]
Fixed. Thanks for reporting!
