### ISSUE TITLE
/events geht bei warp2 mit 1.0.2 firmware nicht

### ISSUE THREAD

**Issue by osr00** [Tinkerforge/warp-charger#12]
http://.../events lässt sich nicht aufrufen bei Warp2

Kann nicht genau sagen ob das jetzt an der neuesten Firmware 1.0.2, am deaktivierten LAN oder ein generelles Problem ist.

Mit der 1.2.4 bei einer Warp1 läuft alles ganz normal.

Bei beiden wurde der integrierte Access Point komplett deaktiviert und sofern vorhanden LAN komplett deaktiviert und der Zugriff erfolgt nur über WLAN.

**Comment by rtrbt** [comment]
Gefixt mit cc11c83f
