### ISSUE TITLE
Ladeaufstellung CSV o.ä.

### ISSUE THREAD

**Issue by ChGalle** [Tinkerforge/warp-charger#14]
Wäre es möglich ein Lade-Log in die Weboberfläche zu integrieren, worin alle Ladevorgänge mit Timestamp, Ladedauer, geladene kWh und Zählerstand erfasst werden? 

Diese könnte man dann bei Bedarf herunterladen und in Excel o.ä. auswerten um dann seine "Stromkosten" mit der Haushaltskasse abzurechnen.

Wenn dieses Projekt nicht ca. 100x größer wäre als meine üblichen ESP32 Projekte, würde ich ja gern was dazu beisteuern. ;-)

**Comment by Metro82** [comment]
Gibt es schon einen ungefähren Zeitplan zu dem Thema?

**Comment by rtrbt** [comment]
Das wird das nächste große Feature für die Firmware. Details zur Umsetzung gbt es hier: https://github.com/Tinkerforge/esp32-firmware/issues/3
Bezüglich ungefährem Zeitplan: Ich gehe davon aus, dass es keine drei Monate dauern wird. Also Richtung Januar, spätestens Februar sollte es das zumindest in rudimentärer Form geben.

**Comment by rtrbt** [comment]
Das Lade-Log ist mit Firmware 2.0.0 implementiert.
