### ISSUE TITLE
Betriebsanleitung: werkseitige Zuleitung - Farben vertauscht

### ISSUE THREAD

**Issue by bboehmke** [Tinkerforge/warp-charger#16]
Ich glaube auf Seite 6 sind die Farben der Adern der werkseitigen Zuleitung vertauscht.

https://github.com/Tinkerforge/warp-charger/blob/1d027f9f8e5a45e090ab0a60f7bffc46381f6837/manual/manual_warp2.tex#L381

müsste glaube ich nach der DIN so aussehen:

```
folgt zugeordnet: L1 braun, L2 schwarz, L3 grau, N blau, PE gelb/grün.
```

**Comment by rtrbt** [comment]
Das stimmt, das ist auf dem Bild korrekt aber im Text verdreht. Ist mit 4a346c7 gefixt. Danke fürs melden!
