### ISSUE TITLE
WARP2 Charger Webinterface Screenshots for warp-charger.com

### ISSUE THREAD

**Issue by batti** [Tinkerforge/warp-charger#24]
We want to have webinterface screenshots at warp-charger.com for the most important functions. These screenshots should include header + nav such that the viewer could get an impression of the interface.

**Comment by m1lk0** [comment]
I would rather recommend to run the webinterface on simulation level in order to get the best user experience while having a real interaction on the latest firmware version.
When I bought my warps I wished I could have even more user experience on the web interface

**Comment by rtrbt** [comment]
Fixed with c1e7831. New issue for a simulated charger here:  #31
