### ISSUE TITLE
Ladecontroller Tastereinstellung nicht persistent 

### ISSUE THREAD

**Issue by binarybucks** [Tinkerforge/warp-charger#26]
Ich verwende den Taster der WARP2 Wallbox zum Schließen des Garagentores über MQTT. 
Hierzu ist die Tastereinstellung auf Keine Aktion gesetzt. 
Leider verliert die Wallbox sporadisch diese Einstellung und die Tastereinstellung wird auf den Default Ladestart bzw. Ladestop zurückgesetzt, so dass der Ladevorgang manchmal unerwartet gestoppt wird. 

Aktuell installierte Firmware: 2.0.8-63218f23

**Comment by borg42** [comment]
Mh, kann es sein dass die Wallbox vom Strom getrennt wird sonst irgendwie neustartet? Die Tastereinstellung ist aktuell nicht persistent, d.h. bei einem Neustart wird sie wieder zurück gesetzt auf die Defaulteinstellung.

Vielleicht sollte die allerdings persistent sein.

**Comment by binarybucks** [comment]
Eigentlich nicht. 
Laufzeit aktuell 11 Tage, 17:26:35. 
Danach wurde der Taster einmal neu gesetzt. Heute hatte er wieder seine Einstellung vergessen. 

Generell wäre es gut, wenn die Einstellungen auch nach einem Neustart persistent sind. Die anderen Einstellungen sind es ja auch, oder?

**Comment by borg42** [comment]
Ja ich geb dir recht, die Einstellung sollte auch persistent sein, baue ich für die nächste Firmware-Version ein. Ich weiß gar nicht warum sie nicht persistent ist.

Allerdings ist es trotzdem komisch dass dein WARP Charger die Einstellung vergisst ohne einen Neustart :thinking:.

**Comment by rtrbt** [comment]
> Laufzeit aktuell 11 Tage, 17:26:35.

Sicherheitshalber: Ist das die Laufzeit des Ladecontrollers (aus der entsprechenden Unterseite)?

**Comment by binarybucks** [comment]
> Sicherheitshalber: Ist das die Laufzeit des Ladecontrollers (aus der entsprechenden Unterseite)?

Genau

**Comment by rtrbt** [comment]
WARP2 Firmware 2.0.9, die ich gerade veröffentlicht habe, speichert die Einstellungen jetzt persistent. Falls die Einstellungen sich bei dir (vorallem ohne bewussten Neustart!) nochmal zurücksetzen, mach das Issue bitte wieder auf.
