### ISSUE TITLE
Charge Tracker Numbers behind comma not working

### ISSUE THREAD

**Issue by fr-Fabix** [Tinkerforge/warp-charger#27]
I try to enter ct/kWh like 25,80 but after press the "Save" Button, I See only 25,00.

Tested with

Mac OS 13.1 with Safari 16.2 and Chrome 109.X. with the same Issue.

WARP Charger 1 with 2.0.9

I tried a point as separator but it does not help.

![image](https://user-images.githubusercontent.com/107420972/214301885-a68ec5ec-4371-4d85-99e3-c77e62e4e8ac.png)

**Comment by rtrbt** [comment]
There were some issues with validating the input: https://github.com/Tinkerforge/esp32-firmware/commit/0797b8e44b54396ee4869d65171fc657b690d64a and https://github.com/Tinkerforge/esp32-firmware/commit/918ea9b623cfcbcc7b49234a7b1d00c549590b21

Those are fixed now and will be released with the next firmware version. Thanks for the bug report!
