### ISSUE TITLE
Feature Request: Freitext-Feld zur Angabe von Bezeichnungen für NFC Tags

### ISSUE THREAD

**Issue by HobbyIngenieur** [Tinkerforge/warp-charger#33]
Zur Vereinfachung der Verwaltung von NFC-Tags würde ich gern Bezeichnungen eingeben und speichern können. Nicht alle Tags/Karten/Tokens haben ihre Nummer auch aufgedruckt.

[BTW: Das ist mein erster Request dieser Art. Falls hier äußere Form oder weitere Infos fehlen - let me know ;-) ]

**Comment by rtrbt** [comment]
Gute Idee! Habe ein Issue in der Firmware dafür aufgemacht.
