### ISSUE TITLE
Power history doesn't show any data

### ISSUE THREAD

**Issue by andreas-bulling** [Tinkerforge/warp-charger#37]
I am running firmware 1.0.91-65492465 on the EnergyManager and added a Fronius inverter using the new Sunspec protocol. The inverter got detected fine and is reporting values but these are not shown in the graph at the top.

![image](https://github.com/Tinkerforge/warp-charger/assets/377856/6fb68778-0d32-455e-b390-2d24073e6022)
![image](https://github.com/Tinkerforge/warp-charger/assets/377856/8826f141-ce73-4f09-a744-2d5b7caa24d7)

**Comment by MattiasTF** [comment]
This should be fixed in beta 5.

**Comment by andreas-bulling** [comment]
will try and report back...

**Comment by andreas-bulling** [comment]
works fine with beta 5

**Comment by andreas-bulling** [comment]
stopped working again yesterday without having changed anything in the configuration

**Comment by andreas-bulling** [comment]
Mine indeed does but there were also no values during the day for some reason. Now they are back...
