### ISSUE TITLE
Anzeige GPIO Low-Level-Zustand flackert 

### ISSUE THREAD

**Issue by 22kW** [Tinkerforge/warp-charger#5]
Ist das dauerhaft unstete Verhalten der GPIO Anzeige beabsichtigt? 

<img width="1122" alt="GPIO" src="https://user-images.githubusercontent.com/3041121/111594607-8e461300-87cb-11eb-827b-5f55268d48f1.png">

https://user-images.githubusercontent.com/3041121/111594628-956d2100-87cb-11eb-8e97-8f2ecb2d534f.mov

**Comment by borg42** [comment]
"Ausgang" ist die LED, da wird Low angezeigt wenn das PWM des atmen unter 50% ist high wenn es über 50% ist
"Motoreingangsschalter" ist auf dem EVSE ein Eingang für Wallboxen mit integrierter Buchse die einen Motor haben um das Kabel zu verriegeln. Dieser Eingang ist beim WARP Charger ungenutzt und floating und er kann entsprechend beliebige Werte anzeigen.

**Comment by 22kW** [comment]
aha, dann würde ich aber einen pull-up oder pull-down Widerstand für den Eingang empfehlen. Evtl. kann man das je nach Mikrocontroller auch intern aktivieren.

**Comment by borg42** [comment]
Ah sorry, ich wurde gerade von meinem Kollegen korrigiert. Bei Wallboxen ohne Motorverriegelung (wie dem WARP Charger) wird eine Diode angebracht zwischen der LED und dem "Motoreingangsschalter". Anhand dieser Diode wird erkannt dass die Wallbox ein angeschlagenes Kabel hat. Dadurch sind "Ausgang" und "Motoreingangsschalter" so gekoppelt.

**Comment by 22kW** [comment]
ok, für den Laien sah das nur alles sehr floating aus, aber wenn es so seine Richtigkeit hat ist ja gut.
